version: '3.8'
services:
  pytrack:
    build: .
    image: pytrack:dev
    ports:
    - "5000:5000"
    volumes:
    - ./:/usr/src/app
    command: flask run --host=0.0.0.0
    environment:
      - FLASK_APP=api.py
      - FLASK_ENV=development
      - PYTRACK_DB=${PYTRACK_DB}